app/officescope/models.py
from app import db
from app.officescope import constants as USER
from datetime import datetime
import uuid


class User(db.Model):
    id = db.Column(db.String(100), primary_key=True)
    name = db.Column(db.String(100))
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    pw_hash = db.Column(db.String(100))

    folders = db.relationship('Folder', backref='owner', lazy='dynamic')
    documents = db.relationship('Document', backref='owner', lazy='dynamic')
    favorites = db.relationship('Favorite', backref='user', lazy='dynamic')

    def __init__(self, name, username, email, pw_hash):
        self.id = unique_id()
        self.name = name
        self.username = username
        self.email = email
        self.pw_hash = pw_hash

    def __repr__(self):
        return '<User %r>' % self.username


class Folder(db.Model):
    id = db.Column(db.String(100), primary_key=True)
    title = db.Column(db.String(80))
    path = db.Column(db.String(1000))
    target = db.Column(db.String(1000))
    add_date = db.Column(db.DateTime)
    folder_id = db.Column(db.String(100), db.ForeignKey('folder.id'))
    owner_id = db.Column(db.String(100), db.ForeignKey('user.id'))

    subfolders = db.relationship('Folder',
        backref=db.backref('parent_folder', remote_side=[id]),lazy='dynamic')
    documents = db.relationship('Document', backref='parent_folder',
        lazy='dynamic')
    favorites = db.relationship('Favorite', backref='folder', lazy='dynamic')





    def __init__(self, title, path, target, add_date=None):
        self.id = unique_id()
        self.title = title
        self.path = path
        self.target = target
        if add_date is None:
            add_date = datetime.utcnow()
        self.add_date = add_date

    def __repr__(self):
        return '<Folder %r>' % self.title

class Document(db.Model):
    id = db.Column(db.String(100), primary_key=True)
    title = db.Column(db.String(80))
    folder_url = db.Column(db.String(1000))
    download_url = db.Column(db.String(1000))
    add_date = db.Column(db.DateTime)
    owner_id = db.Column(db.String(100), db.ForeignKey('user.id'))
    folder_id = db.Column(db.String(100), db.ForeignKey('folder.id'))



    def __init__(self, title, folder_url, download_url, add_date=None):
        self.id = unique_id()
        self.title = title
        self.folder_url = folder_url
        self.download_url = download_url
        if add_date is None:
            add_date = datetime.utcnow()
        self.add_date = add_date

    def __repr__(self):
        return '<Document %r>' % self.title


class Favorite(db.Model):
    user_id = db.Column(db.String(100), db.ForeignKey('user.id'), primary_key=True)
    folder_id = db.Column(db.String(100), db.ForeignKey('folder.id'), primary_key=True)



#returns a unique id
def unique_id():
    return hex(uuid.uuid4().time)[2:-1]

def get_user_name(id):
    user = User.query.filter_by(id=id).first()
    username = user.name
    return username

app/officescope/views.py
#!/usr/bin/lib/env python
# -*- coding: utf-8 -*-

from __future__ import with_statement

import os.path

from flask import (Blueprint, Flask, request, session, url_for, redirect,
        render_template, abort, g, flash, _app_ctx_stack)
from werkzeug import check_password_hash, generate_password_hash
from flask.ext.uploads import (UploadSet, configure_uploads, DEFAULTS,
        UploadNotAllowed)

from app import db
from app import app

from models import get_user_name, User, Document, Folder, Favorite

#Uploads
uploaded_files = UploadSet('files', DEFAULTS)
configure_uploads(app, uploaded_files)

officescope = Blueprint('officescope', __name__)

@officescope.before_request
def before_request():
    """Sets user id to g object if not available in session already."""
    g.user = None
    if 'user_id' in session:
        g.user = User.query.filter_by(id=session['user_id']).first()


@officescope.route('/about')
def about():
    return 'about'


# TODO: Change this logic... complex is better than complicated
@officescope.route('/', defaults={'path': 'home'})
@officescope.route('/home', defaults={'path': 'home'})
@officescope.route('/<path:path>')
def home(path):
    """Shows a list of folders and documents owned by the user. The home page also
    shows a list of favorites the user has added. If the user is not session, it will
    redirect to the login page."""
    if g.user:
        """ TODO
        if not path_exists(path):
            flash("Folder '%s' does not exist" % path)
            return redirect(url_for('home', path='home'))
        """
        folders = Folder.query.filter(Folder.owner_id == g.user.id,
            Folder.path == path).all()
        documents = Document.query.filter(Document.owner_id == g.user.id,
            Document.folder_url == path).all()
        favorites = Favorite.query.join(Folder).filter(Favorite.user_id == g.user.id,
            Folder.id == Favorite.folder_id).all()
        return render_template('officescope/home.html', folders=folders, documents=documents,
            parent_path=path, favorites=favorites)
    else:
        return redirect(url_for('officescope.login'))


@officescope.route('/<path:path>/create', methods=['POST'])
def create_folder(path):
    """Creates a new folder in the provided path"""
    if not g.user:
        return redirect(url_for('login'))
    #error = None
    if g.user and request.method =='POST':
        parent_folder = Folder.query.filter(Folder.owner_id == g.user.id,
            Folder.target == path).first()
        if parent_folder.owner_id != g.user.id:
            abort(401)
        target_url = '%s/%s' % (path, request.form['folder_name'])
        new_folder = Folder(request.form['folder_name'], path, target_url)
        #folder backref
        new_folder.parent_folder = parent_folder
        new_folder.owner = g.user
        db.session.add(new_folder)
        db.session.commit()
        return redirect(url_for('officescope.home', path=path))


@officescope.route('/<path:path>/<folder_id>/favorite')
def add_favorite(path, folder_id):
    """Adds a new favorite folder into favorites"""
    if not g.user:
        return redirect(url_for('officescope.login'))
    #error = None
    if g.user:
        favorite_folder = Folder.query.filter_by(id=folder_id).first()
        new_favorite = Favorite()
        new_favorite.user = g.user
        new_favorite.folder = favorite_folder
        db.session.add(new_favorite)
        db.session.commit()
        return redirect(url_for('officescope.home', path=path))


@officescope.route('/<path:path>/<folder_id>/delete')
def delete_folder(path, folder_id):
    """Wrapper for delet_folder_recursively and returns to the path of origin."""
    if not g.user:
        return redirect(url_for('officescope.login'))
    if g.user:
        delete_folder_recursively(folder_id)
        return redirect(url_for('officescope.home', path=path))


def delete_folder_recursively(parent_folderid):
    """Deletes a folder recursively as well as any favorites and documents contained
    by the folder."""
    subfolders = Folder.query.filter(Folder.owner_id == g.user.id,
                                  Folder.folder_id == parent_folderid).all()
    folder_to_delete = Folder.query.filter(Folder.owner_id == g.user.id,
                                           Folder.id == parent_folderid).first()
    favorite_to_delete = Favorite.query.filter(Favorite.user_id == g.user.id,
                                               Favorite.folder_id == parent_folderid).first()
    documents_to_delete = Document.query.filter(Document.owner_id == g.user.id,
                                                Document.folder_id == parent_folderid).all()

    for subfolder in subfolders:
        delete_folder_recursively(subfolder.id)
    if favorite_to_delete:
        db.session.delete(favorite_to_delete)
    for document in documents_to_delete:
        delete_document_and_unlink(document.id)
    db.session.delete(folder_to_delete)
    db.session.commit()



@officescope.route('/<path:path>/<doc_id>/delete_document')
def delete_document(path, doc_id):
    """Wrapper for delete_document_and_unlink. Redirects to path of origin."""
    if not g.user:
        return redirect(url_for('officescope.login'))
    #error = None
    if g.user:
        delete_document_and_unlink(doc_id)
        return redirect(url_for('officescope.home', path=path))


def delete_document_and_unlink(doc_id):
    """Deletes a particular document and also unlinks the document from disk."""
    document_to_delete = Document.query.filter_by(id=doc_id).first()
    file_to_delete = app.config['UPLOADED_FILES_DEST'] + document_to_delete.title
    db.session.delete(document_to_delete)
    db.session.commit()
    if os.path.isfile(file_to_delete):
        os.remove(file_to_delete)


@officescope.route('/<path:path>/upload', methods=['POST'])
def upload_file(path):
    """Uploads a file to the supplied path and creates a new document."""
    if not g.user:
        return redirect(url_for('officescope.login'))
    #error = None
    if g.user and request.method == 'POST' and ('file' in request.files):
        parent_folder = Folder.query.filter(Folder.owner_id == g.user.id,
            Folder.target == path).first()
        if parent_folder.owner_id != g.user.id:
            abort(401)
        try:
            filename = uploaded_files.save(request.files['file'])
            file_url = uploaded_files.url(filename)
            new_document = Document(title=filename, folder_url=parent_folder.target,
                download_url=file_url)
            #documents backref
            new_document.parent_folder = parent_folder
            new_document.owner = g.user

            db.session.add(new_document)
            db.session.commit()
        except UploadNotAllowed:
            flash("Failed to upload file.")

        return redirect(url_for('officescope.home', path=path))


@officescope.route('/login', methods=['GET', 'POST'])
def login():
    """Logs the user in."""
    if g.user:
        return redirect(url_for('officescope.home'))
    error = None
    if request.method == 'POST':
        user = User.query.filter_by(username=request.form['username']).first()

        if user is None:
            error = 'Invalid username'
        elif not check_password_hash(user.pw_hash, request.form['password']):
            error = 'Invalid password'
        else:
            flash('You were logged in')
            session['user_id'] = user.id
            return redirect(url_for('officescope.home'))
    return render_template('officescope/login.html', error=error)


@officescope.route('/logout')
def logout():
    """Logs the user out."""
    if g.user:
        session.pop('user_id', None)
        flash('You were logged out')
        return redirect(url_for('officescope.login'))


@officescope.route('/register', methods=['GET', 'POST'])
def register():
    """Registers the user."""
    if g.user:
        return redirect(url_for('officescope.home'))
    error = None
    if request.method == 'POST':
        if not request.form['username']:
            error = 'You have to enter a username'
        elif not request.form['email'] or \
            '@' not in request.form['email']:
            error = 'You have to enter a valid email address'
        elif not request.form['password']:
            error = 'You have to enter a password'
        elif request.form['password'] != request.form['password2']:
            error = 'The two passwords do not match'
        elif User.query.filter_by(username=request.form['username']).first() is not None:
            error = 'The username is already taken'
        else:
            user = User(request.form['fullname'], request.form['username'],
                request.form['email'], generate_password_hash(request.form['password']))
            new_folder = Folder('home', 'ROOT', 'home')
            new_folder.owner = user
            db.session.add(user)
            db.session.add(new_folder)
            db.session.commit()
            flash('You were successfully registered and can login now')
            return redirect(url_for('officescope.login'))
    return render_template('officescope/register.html', error=error)

#jinja filters
app.jinja_env.filters['getusername'] = get_user_name

app/templates/officescope/home.html
{% extends "layouts/officescope.html" %}
{% block title %}Home{% endblock %}
{% block style %}{% endblock %}
{% block body %}

<div class="container">
	<div class="row">
		<div class="span2">
			<div class="well sidebar-nav favorites">
				<ul class="nav nav-list">
					<li class="nav-header">Favorites</li>
					{% for favorite in favorites %}
					<li>
						<a href="{{ url_for('officescope.home', path=favorite.folder.target) }}">{{ favorite.folder.title }}</a>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>
		<div class="span10">
			<div class="row">
				<div class="span5">
					<div class="form-inline">
						<form action="{{ url_for('officescope.create_folder', path=parent_path) }}" method="POST">
							<fieldset>
								<input type="text" name="folder_name" placeholder="New folder...">
								<button type="Submit" class="btn">Create</button>
							</fieldset>

						</form>
					</div>
				</div>
				<div class="span5">
					<div class="form-inline pull-right">
						<form action="{{ url_for('officescope.upload_file', path=parent_path) }}" method="POST" enctype=multipart/form-data>
							<fieldset>
								<input type="file" name="file">
								<button type="Submit" class="btn">Import</button>
							</fieldset>

						</form>
					</div>
				</div>
			</div>
			<div class="browse">
				<!--<div class="previous">
					{{ previous }}
				</div>-->
				<table class="table table-hover">
					<thead>
						<tr>
							<th>Name</th>
							<th>Type</th>
							<th>Created at</th>
							<th>Created by</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						{% for folder in folders  %}
						<tr>
							<td class="folder_icon"><a href="{{ url_for('officescope.home', path=folder.target) }}">{{ folder.title }}</a></td>
							<td>Folder</td>
							<td>{{ folder.add_date }}</td>
							<td>{{ folder.owner_id|getusername }}</td>
							<td><a href="{{ url_for('officescope.add_favorite', path = parent_path, folder_id = folder.id) }}"><img src="{{ url_for('static', filename='officescope/img/favorite.png') }}"></a> <span class="delete"><a href="{{ url_for('officescope.delete_folder', path = parent_path, folder_id = folder.id) }}"><img src="{{ url_for('static', filename='officescope/img/delete.png') }}"></a></span></td>
						</tr>
                        {% else %}
                        <tr>
                            <td>
                                <span class="label label-info">Start by creating a new folder</span>
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    	{% endfor %}

						{% for document in documents  %}
						<tr>
							<td class="document_icon"><a href="{{ document.download_url }}">{{ document.title }}</a></td>
							<td>..</td>
							<td>{{ document.add_date }}</td>
							<td>{{ document.owner_id|getusername }}</td>
							<td><span class="delete_doc"><a href="{{ url_for('officescope.delete_document', path=parent_path, doc_id = document.id) }}"><img src="{{ url_for('static', filename='officescope/img/delete.png') }}"></td>
						</tr>
                        {% else %}
                        <tr>
                            <td>
                            <span class="label label-info">Start by importing a document</span>
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
						{% endfor %}
					</tbody>

				</table>

			</div>
		</div>

	</div>
    <hr>
</div>
{% endblock %}

app/templates/officescope/login.html
{% extends "layouts/officescope.html" %}
{% block title %}Sign In{% endblock %}
{% block style %}
body {
    padding-top: 60px;
    padding-bottom: 40px;
    background-color: #f5f5f5;
}
{% endblock %}
{% block body %}
	<div class = "container">
		<form class="form-box" action="{{ url_for('officescope.login') }}" method="POST">
			<h2 class="form-signin-heading">Please sign in</h2>
			{% if error %}<div class=error><strong>Error:</strong> {{ error }}</div>{% endif %}
			<input type="text" class="input-block-level" name=username placeholder="Username">
			<input type="password" class="input-block-level" name=password placeholder="Password">
			<label class="checkbox">
				<input type="checkbox" value="remember-me">Remember me
			</label>
			<button class="btn btn-large btn-primary" type="submit">Sign in</button>
		</form>
	</div>
{% endblock %}

app/templates/officescope/register.html
{% extends "layouts/officescope.html" %}
{% block title %}Register{% endblock %}
{% block style %}
body {
    padding-top: 60px;
    padding-bottom: 40px;
    background-color: #f5f5f5;
}
{% endblock %}
{% block body %}
<div class = "container">
	<form class="form-box" action="{{ url_for('officescope.register') }}" method="POST">
		<h2 class="form-register-heading">Please Register</h2>
		{% if error %}<div class=error><strong>Error:</strong> {{ error }}</div>{% endif %}
		<input type="text" class="input-block-level" name=fullname placeholder="Name">
    <input type="text" class="input-block-level" name=username placeholder="Username">
    <input type="text" class="input-block-level" name=email placeholder="Email">
		<input type="password" class="input-block-level" name=password placeholder="Password">
    <input type="password" class="input-block-level" name=password2 placeholder="Confirm Password">
		<button class="btn btn-large btn-primary" type="submit">Sign up</button>
	</form>
</div>
{% endblock %}